variables:
  DOCKER_IMAGE_FULLNAME: $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_NODE_IMAGE: docker-registry.esrf.fr/dau/node:14.18.2
stages:
  - test

Lint:
  stage: test
  image: $DOCKER_NODE_IMAGE
  script:
    - npm ci
    - npm run lint


