site_name: EXI2
site_url: https://ispyb.gitlab-pages.esrf.fr/exi2
repo_name: 'ispyb/EXI2'
repo_url: 'https://gitlab.esrf.fr/ispyb/exi2'
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Installation: installation.md
  - Developments: developments.md
  - FAQ: faq.md


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      custom_templates: templates
      watch:
        - ../../exi2

markdown_extensions:
  - codehilite
  - attr_list
  - admonition
